### ISSUE TITLE
推理时对于中文解码，是怎么处理的？

### ISSUE THREAD

**Issue by echoht** [AndrewZhe/lawyer-llama#11]
您好，已经了解了continue pretrain没有做进一步词表扩充，那解码的时候，对于中文是怎么恢复的呢？

**Comment by AndrewZhe** [comment]
continual pretrain 是否要扩充词表，主要看你对生成效率的要求。如果追求生成速度的话，需要阔词表。

原生的llama主要用utf-8编码中文呀，相当于decode出三个token，然后拼在一起，作为一个中文字符。
