### ISSUE TITLE
想要跟ChatGPT官网一样的可以分享整个聊天记录的功能和接受用户评价（点赞和点踩）的功能，以及关于开源软件许可证方面的优化建议

### ISSUE THREAD

**Issue by PolarisRisingWar** [AndrewZhe/lawyer-llama#13]
1. 我现在跟模型产生了互动，形成了一个完整的聊天记录，想要分享整个聊天记录，或者保存整个聊天记录。
2. 现在想要通过模型输出产生反馈似乎只能通过提issue的方式？您可以尝试像ChatGPT一样直接在网站上设置用户通过对模型回复进行点赞/点踩/评论等功能，来直接收集用户的反馈。
3. 我咨询模型关于开源软件许可证的相关事宜，感觉模型应该有收集一些信息，但是主要问题是所知的事实信息不全（比如不知道MulanPSL-2.0），其次是输出的建议比较模糊、大而化之（但这一点应该是很多LLM的通病，而且似乎本来就建议通过人工进一步操作来进行细化）。
感觉仅供参考的话还是有价值的，但是仍然可以改进，总之我也给您这边提一下这个情况。我的对话历史是：
![image](https://github.com/AndrewZhe/lawyer-llama/assets/48322321/dc72c7b3-fe68-4e9a-9a34-9926e4d16680)
![image](https://github.com/AndrewZhe/lawyer-llama/assets/48322321/d3a8468c-d70f-41ea-83e3-025ce079e8fe)
![image](https://github.com/AndrewZhe/lawyer-llama/assets/48322321/09981784-454c-4531-8ed7-89df036ad9d6)
![image](https://github.com/AndrewZhe/lawyer-llama/assets/48322321/bb7ba65a-6744-4ca0-9256-b7741f069e57)
4. 另外就是，我能够输入GPT-3.5 API的文本长度似乎不能完全输入Lawyer LLaMA，想问一下Lawyer LLaMA的输入输出限长是多少呢？

**Comment by PolarisRisingWar** [comment]
补一个GPT-3.5-turbo对第一个问题的回答吧：

用户输入是：我开设了一个对LLM（大规模预训练语言模型）进行整理的Gitee resporitory，现在用木兰宽松许可证（MulanPSL-2.0）来作为这个resporitory的许可证，请问我在面临什么侵权行为（如抄袭等）时，可以通过什么方式来维护自己的权益？

GPT回答是：
作为MulansPSL-2.0的许可证使用者，您有权保护自己的著作权和知识产权。如果您发现有人侵犯了您的权益，您可以采取以下措施：

1.联系侵权方并要求其停止侵犯您的权益，并在规定时间内删除侵权内容。如果侵权方同意您的要求，可以达成和解，否则可以进行下一步操作。

2.向相关政府部门投诉，要求其介入调查侵权行为，并制止侵权。政府部门有权采取行政措施来打击侵权行为。

3.通过法律途径维护自己的权益。如果侵权行为已经严重影响了您的利益，建议您通过法律诉讼来解决，在法庭上要求侵权方承担相应的责任。

无论采取哪种方式，都建议您在维护自己权益的过程中，保留相关的证据，例如侵权方的网页截图、邮件通信内容等等，以便证明您的权益遭到了侵犯。

**Comment by AndrewZhe** [comment]
非常感谢您的反馈！

确实我们现在的UI，还没有地方提供用户反馈，我们后续会添加这个功能的！

关于开源软件许可证的相关事宜，事实不准：事实不准 或者 幻觉确实是现在大模型的通病。我们尝试通过外挂一个检索模块，去搜索相关信息作为额外的知识，来让模型回答的更准确一些。目前，我们主要针对婚姻相关的咨询问题，设计了检索模块。后续我们会将这一模块扩展到通用的法律领域，相信能对你反馈的这类问题有所帮助。
