### ISSUE TITLE
关于marriage article retrieval托管方式的建议

### ISSUE THREAD

**Issue by LeetJoe** [AndrewZhe/lawyer-llama#15]
### 冒昧提一个小建议
我注意到开源出的lawyer llama13b里有用到一个marriage article retrieval项目，但是代码是通过百度网盘分享的。为什么不直接创建一个git仓库呢，使用[git lfs](https://docs.github.com/en/repositories/working-with-files/managing-large-files/configuring-git-large-file-storage)可以解决大文件问题。
还是出于某些别的考虑呢？

**Comment by luciusssss** [comment]
感谢您的建议！marriage article retrieval的里模型比较大，传到git上后对一些用户来说下载起来不太方便。我们之后会考虑将marriage article retrieval里的代码部分使用github托管。

**Comment by LeetJoe** [comment]
很贴心的考虑。了解了，谢谢。
