### ISSUE TITLE
关于预训练数据规模的问题

### ISSUE THREAD

**Issue by cnzx05cnzx** [AndrewZhe/lawyer-llama#17]
能透露一下预训练数据中，通用语料与法律领域的数据规模分别有多少呢？

**Comment by AndrewZhe** [comment]
约10B 这个量级。

不过可能数据量还是越多越好

**Comment by mynewstart** [comment]
请问10B是指token的数量吗？如果要continue pretraining 13B这个规模的模型，大概需要多少卡，训练多久？

**Comment by AndrewZhe** [comment]
> 请问10B是指token的数量吗？

是的

> 如果要continue pretraining 13B这个规模的模型，大概需要多少卡，训练多久？

全参的话，至少需要8卡，2周+
