### ISSUE TITLE
解码需要llama-13-hf吗

### ISSUE THREAD

**Issue by sssdjj** [AndrewZhe/lawyer-llama#19]
![image](https://github.com/AndrewZhe/lawyer-llama/assets/13341798/93217d6e-2859-4fa7-86cd-aac20da08130)
是不是我直接 下载 
通过[Hugging Face](https://huggingface.co/pkupie/lawyer-llama-13b-beta1.0)或者[百度网盘](https://pan.baidu.com/s/1cE9_c8er3NASpDkFou-B9g?pwd=lwhx)（提取码：lwhx）获取Lawyer LLaMA权重。

利用原始LLaMA文件中的7B/consolidated.00.pth文件，运行以下bash命令，使用decrypt.py对Lawyer LLaMA模型文件进行解码。

就可以得到 权重了，需要下载 llama-13-hf吗

**Comment by luciusssss** [comment]
不需要下载 llama-13-hf，只需要原始LLaMA-7B里consolidated.00.pth。
