### ISSUE TITLE
continue training样本

### ISSUE THREAD

**Issue by kakaxisisan** [AndrewZhe/lawyer-llama#2]
请问continue training的时候的样本是怎么处理的？具体的输入到模型的每条样本都是什么样的？

**Comment by AndrewZhe** [comment]
纯文本截断成512的长度，然后法律文本和通用语料混合起来一起训练

**Comment by ReverseSystem001** [comment]
比如一篇文章，提取出来文本，直接截断成512长度为一个sample，会不会出现一个句子分成两段，在两个sample中啊，这样训练时，不会对结果有影响吗
