### ISSUE TITLE
marriage article retrieval模块的作用以及拓展模块疑问

### ISSUE THREAD

**Issue by cason0126** [AndrewZhe/lawyer-llama#21]
请问：
1、marriage article retrieval的额外模块的作用是什么？是对婚姻法的检索么？是指检索XX条XX做出回答吗？其必要性是什么？
2、明确说明了是婚姻法，如果想扩增/修改 其他相关法律条例，是否也是按照这种模式增加呢？

**Comment by luciusssss** [comment]
1. 该模块用于对婚姻相关的咨询，检索相关的法条，辅助模型生成更可信的回复。

2. 是的。如果想扩增/修改 其他相关法律条例，可以自己设计/训练法条检索器，接在Lawyer LLaMA上。

**Comment by cason0126** [comment]
明白，谢谢。
