### ISSUE TITLE
上下文遗忘和速度下降

### ISSUE THREAD

**Issue by qinxiandiqi** [AndrewZhe/lawyer-llama#23]
大概3轮或4轮对话后，会遗忘部分上下文，并且回答速度急速下降。

**Comment by AndrewZhe** [comment]
长距离依赖一直是大模型的挑战之一。
我们目前的模型，主要面向的场景是咨询，通常对话的轮次就在3轮左右，并没有针对更长的对话做优化。

回答速度方面，因为模型需要考虑历史信息，因此轮次越多，输入长度越大，模型的速度就会越慢。
