### ISSUE TITLE
demo_cmd.py报错HTTPConnectionPool(host='127.0.0.1', port=9098): Max retries exceeded with url:

### ISSUE THREAD

**Issue by yan-rui** [AndrewZhe/lawyer-llama#25]
感谢作者分享这和repo。
我在运行的时候遇到了这个报错，检查了防火墙，还是无法链接9098这个接口
可以帮忙看看是什么问题吗
[error_demo_web.txt](https://github.com/AndrewZhe/lawyer-llama/files/11798819/error_demo_web.txt)

**Comment by luciusssss** [comment]
我们没有遇到过这个问题。你可以尝试换一个别的端口？或者试一下把`demo.launch(share=False, server_port=args.port, server_name='0.0.0.0')`里的`0.0.0.0`换成`127.0.0.1`？

**Comment by yan-rui** [comment]
感谢大佬回复，经过检查，发现是我的防火墙没有设置正确导致的
