### ISSUE TITLE
Error: "pytorch_model-00002-of-00003.bin"Checksums do not match. The file may be corrupted.

### ISSUE THREAD

**Issue by sjkjsandy** [AndrewZhe/lawyer-llama#27]
Decrypting file /lawyer-llama-13b-beta1.0/pytorch_model-00002-of-00003.bin.58352e4e890197aa518502ba6ea6f4fad0918d01fa64b630562bf163d46754a3.enc with 127 workers
Writing final chunks...
Error: Checksums do not match. The file may be corrupted.

请教一下，试过几次了，从https://huggingface.co/pkupie/lawyer-llama-13b-beta1.0/tree/main，下载的“pytorch_model-00002-of-00003.bin.58352e4e890197aa518502ba6ea6f4fad0918d01fa64b630562bf163d46754a3.enc”文件，在解密后做chunks时一直报错。

**Comment by luciusssss** [comment]
你好，可能是下载时文件损坏了，可以尝试重新下载一下
