### ISSUE TITLE
retrieval model有更多的细节吗？

### ISSUE THREAD

**Issue by applepieiris** [AndrewZhe/lawyer-llama#29]
technical report中说到retrieval model可以达到0.85recall@1, 但并没有提到这部分训练数据的规模，有更多的细节可以公布吗？感觉这个recall已经让人很吃惊了

**Comment by luciusssss** [comment]
训练时使用了万量级的婚姻领域的数据，在同分布的测试数据上能达到该结果。在实际应用场景下，用户咨询和训练数据的分布差距还是比较远的，检索recall会下降很多。
