### ISSUE TITLE
关于预训练资源和时间的估计

### ISSUE THREAD

**Issue by nuoma** [AndrewZhe/lawyer-llama#3]
你好！首先恭喜，神作！通篇挑不出毛病，且证实了我之前的猜测：1，扩充词表会让中文能力降低，但是不知道ymcui后来推出的plus版本，即增大了增量预训练的语料，会不会有更好的表现。2，经过领域增量训练后，即使是广义的SFT就可以具备应付专业领域的问题了。

anyway跑题了，麻烦可否提供一个计算资源和所需时间的估计，尤其是S1（增量中文训练）和S4（增量法律训练），且这两个阶段的语料库大致是什么样的量级，以及sample articles存在某种策略吗还是随机的，我似乎没有找到这方面的细节。

非常感谢，再次恭喜如此高质量的工作！

**Comment by AndrewZhe** [comment]
谢谢欣赏！

S1 和 S4 这两个阶段，至少需要预留8卡15天的计算资源。在此基础上，才能看到不错的效果。

articles 我们不是sample的，我们是训练了一个法条分类器，根据用户query，去所有法条中搜索相关的法条。具体细节可以参考我们论文的Section 3.4 Retrieving Relevant Law Articles。

**Comment by Kouuh** [comment]
> 你好！首先恭喜，神作！通篇挑不出毛病，且证实了我之前的猜测：1，扩充词表会让中文能力降低，但是不知道ymcui后来推出的plus版本，即增大了增量预训练的语料，会不会有更好的表现。2，经过领域增量训练后，即使是广义的SFT就可以具备应付专业领域的问题了。
> 
> anyway跑题了，麻烦可否提供一个计算资源和所需时间的估计，尤其是S1（增量中文训练）和S4（增量法律训练），且这两个阶段的语料库大致是什么样的量级，以及sample articles存在某种策略吗还是随机的，我似乎没有找到这方面的细节。
> 
> 非常感谢，再次恭喜如此高质量的工作！

没太看懂扩充词表为啥会降低中文能力？？

**Comment by AndrewZhe** [comment]
> > 你好！首先恭喜，神作！通篇挑不出毛病，且证实了我之前的猜测：1，扩充词表会让中文能力降低，但是不知道ymcui后来推出的plus版本，即增大了增量预训练的语料，会不会有更好的表现。2，经过领域增量训练后，即使是广义的SFT就可以具备应付专业领域的问题了。
> > anyway跑题了，麻烦可否提供一个计算资源和所需时间的估计，尤其是S1（增量中文训练）和S4（增量法律训练），且这两个阶段的语料库大致是什么样的量级，以及sample articles存在某种策略吗还是随机的，我似乎没有找到这方面的细节。
> > 非常感谢，再次恭喜如此高质量的工作！
> 
> 没太看懂扩充词表为啥会降低中文能力？？

我们并没有这个结论哈。扩充词表能显著提升解码的速度，但是目前暂没有明确的实验来支持到底是否能带来中文能力的提升。

**Comment by nuoma** [comment]
> > 你好！首先恭喜，神作！通篇挑不出毛病，且证实了我之前的猜测：1，扩充词表会让中文能力降低，但是不知道ymcui后来推出的plus版本，即增大了增量预训练的语料，会不会有更好的表现。2，经过领域增量训练后，即使是广义的SFT就可以具备应付专业领域的问题了。
> > anyway跑题了，麻烦可否提供一个计算资源和所需时间的估计，尤其是S1（增量中文训练）和S4（增量法律训练），且这两个阶段的语料库大致是什么样的量级，以及sample articles存在某种策略吗还是随机的，我似乎没有找到这方面的细节。
> > 非常感谢，再次恭喜如此高质量的工作！
> 
> 没太看懂扩充词表为啥会降低中文能力？？

我记错了，不是在本工作内，而是在其他工作里看到的。扩充词表会打乱原有的分词形式，如果增量预训练不充足的话，会导致eval的分数显著的降低
