### ISSUE TITLE
Error no file named pytorch_model.bin

### ISSUE THREAD

**Issue by wangzff** [AndrewZhe/lawyer-llama#30]
(base) /mnt/workspace/lawyer-llama/demo> python demo_web.py --port 7863 --checkpoint /mnt/workspace/lawyer-llama/lawyer-llama-13b-beta1.0
Loading model...
Traceback (most recent call last):
  File "/mnt/workspace/lawyer-llama/demo/demo_web.py", line 52, in <module>
    model = LlamaForCausalLM.from_pretrained(checkpoint, device_map="auto", torch_dtype=torch.float16)
  File "/home/pai/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2405, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /mnt/workspace/lawyer-llama/lawyer-llama-13b-beta1.0.

**Comment by wangzff** [comment]
这个是啥错误，大佬能解答一下吗

**Comment by luciusssss** [comment]
下载模型文件解密过了吗？看起来是在文件夹里找到能load的模型文件。你能把/mnt/workspace/lawyer-llama/lawyer-llama-13b-beta1.0这个文件夹里的内容列出来看一下吗。

**Comment by wangzff** [comment]
好的，大佬我发您。
![image](https://github.com/AndrewZhe/lawyer-llama/assets/18679682/2542d2d0-4fa7-4428-97ef-eec825871c13)
我这个解密了。

**Comment by luciusssss** [comment]
那可能是transformers库版本太低了，不支持load切分后的模型。可以试试把transformers库更新一下？

**Comment by wangzff** [comment]
(base) /mnt/workspace/lawyer-llama/demo> python demo_web.py --port 7863 --checkpoint /mnt/workspace/lawyer-llama/lawyer-llama-13b-beta1.0
Loading model...
Traceback (most recent call last):
  File "/mnt/workspace/lawyer-llama/demo/demo_web.py", line 52, in <module>
    model = LlamaForCausalLM.from_pretrained(checkpoint, device_map="auto", torch_dtype=torch.float16)
  File "/home/pai/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2449, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /mnt/workspace/lawyer-llama/lawyer-llama-13b-beta1.0. 

transformers库版本4.30.2
pip install transformers==4.30.2
也不好使，已经用最新的了。

**Comment by wangzff** [comment]
大佬能帮忙看看啥问题吗

**Comment by luciusssss** [comment]
抱歉，我们暂时看不出来是什么问题。可以考虑去https://github.com/huggingface/transformers 提issue看看是什么原因。

**Comment by AndrewZhe** [comment]
> 

不知道是不是差一个 pytorch_model.bin.index.json 文件？
我们check一下
