### ISSUE TITLE
作者可以麻烦提供数据集的正确下载地址吗？

### ISSUE THREAD

**Issue by seanzhang-zhichen** [AndrewZhe/lawyer-llama#35]
原始下载地址：https://opendata.pku.edu.cn/api/access/datafile/2112?gbrecs=true无法成功下载数据集，请问是否可以提供一个正确的地址，感激不尽

**Comment by luciusssss** [comment]
你是指华律网法律咨询数据吗？
https://opendata.pku.edu.cn/dataset.xhtml?persistentId=doi:10.18170/DVN/OLO4G8  我们试了一下可以下载。可能是网络环境的原因，你可以换个网络环境试试？

**Comment by aixuedegege** [comment]
其他的可以下载，但是answer1会报错：https://opendata.pku.edu.cn/api/access/datafile/2112?gbrecs=true
