### ISSUE TITLE
训练代码能开源吗？

### ISSUE THREAD

**Issue by merlinarer** [AndrewZhe/lawyer-llama#4]

**Comment by Kouuh** [comment]
同求增量训练代码。

**Comment by AndrewZhe** [comment]
会开源的。
我们优先放一个可用的模型出来，然后再整理各部分训练代码。

**Comment by merlinarer** [comment]
> 会开源的。 我们优先放一个可用的模型出来，然后再整理各部分训练代码。

有大概的release时间吗，另外想请教下各个数据集的量大概是什么样子，paper里没找到，有汇总的表格吗？

**Comment by AndrewZhe** [comment]
我们这周争取先把模型release出来！

数据集的话，基本上都是10K这个量级。

**Comment by merlinarer** [comment]
> 我们这周争取先把模型release出来！
> 
> 数据集的话，基本上都是10K这个量级。

那预训练的两个数据集呢，分别大概多少token呢

**Comment by AndrewZhe** [comment]
中文通用多多益善。

两部分数据，应该都期望至少是10B这个量级。

**Comment by Olivia-xu** [comment]
增量训练的话，能够提供一下相关任务的demo吗？
