### ISSUE TITLE
预训练后的模型能很好复述法规吗

### ISSUE THREAD

**Issue by MikeHollyWong** [AndrewZhe/lawyer-llama#41]
您好，请教下哈，我希望模型能够背诵出一些重要知识，比如法律法规条款，于是在做增量预训练过程中，我增加了相关数据被采样的epoch，loss也下降明显，达到了0.几的水平，但模型还是无法很好地复述相关知识（给提示让模型补全下文）。请问您做预训练有遇到过类似的问题吗，有没啥经验呢。

**Comment by luciusssss** [comment]
经过增量预训练的模型仍有可能在复述法条时出现错误。在实际应用中，通过检索增强可以比较好地解决这种问题。

**Comment by MikeHollyWong** [comment]
感谢答疑
