### ISSUE TITLE
chat_history[:-1] 为什么把最近一次的对话给去掉？

### ISSUE THREAD

**Issue by ReverseSystem001** [AndrewZhe/lawyer-llama#43]
demo_cmd.py  66 行，   chat_history[:-1] 为什么把最近一次的对话给去掉？

**Comment by luciusssss** [comment]
是代码写错了，感谢指出问题，已修复。

**Comment by ReverseSystem001** [comment]
好的



---原始邮件---
发件人: "Chen ***@***.***&gt;
发送时间: 2023年8月30日(周三) 下午3:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [AndrewZhe/lawyer-llama] chat_history[:-1] 为什么把最近一次的对话给去掉？ (Issue #43)




 
是代码写错了，感谢指出问题，已修复。
