### ISSUE TITLE
问下，怎么理解是基于Chinese-LLaMA-13B的呢

### ISSUE THREAD

**Issue by san5167** [AndrewZhe/lawyer-llama#48]
看该[部署文档](https://github.com/AndrewZhe/lawyer-llama/blob/main/demo/run_inference.md)，说模型基于Chinese-LLaMA-13B，不过具体还是基于llama原模型加上Lawyer LLaMA的权重就可以了，这里面涉及了Chinese-LLaMA-13B吗，没太明白了，求大神能指点下迷津。

**Comment by luciusssss** [comment]
你好，我们的模型是基于Chinese-LLaMA-13B训练的。我们公开的是完整的模型参数，但考虑到LLaMA 1的许可证问题，我们对模型参数做了加密，使用LLaMA 1的模型源文件可以对其解密。
