### ISSUE TITLE
[百度网盘链接失效] 请问能更新一下百度网盘的链接吗，“下载法条检索模块”的链接失效了

### ISSUE THREAD

**Issue by llzzllz** [AndrewZhe/lawyer-llama#52]
链接失效
从[百度网盘](https://pan.baidu.com/s/1V9wsQR4ndKNqWRl8lGhOaw?pwd=r0vx)（提取码：r0vx）下载法条检索模块，并运行其中的python server.py启动法条检索服务，默认挂在9098端口。

**Comment by luciusssss** [comment]
你好，已更新 https://pan.baidu.com/s/1tBkgMzcDe3zZ8Xyf22T7Wg
密码:jxqh

**Comment by llzzllz** [comment]
> 你好，已更新 https://pan.baidu.com/s/1tBkgMzcDe3zZ8Xyf22T7Wg 密码:jxqh

非常感谢！
