### ISSUE TITLE
解码出错

### ISSUE THREAD

**Issue by ahpuchend** [AndrewZhe/lawyer-llama#58]
Decrypting file /mnt/nvme0n1/chendong/aiwork/pretrain_hub/lawyer-llama-13b-beta1.0/pytorch_model-00001-of-00003.bin.5e72fa85bd87b107cf04964beb7dc8a2ee310994a7524908ada150b16224908a.enc with 79 workers
Writing final chunks...
Decryption completed.
Decrypting file /mnt/nvme0n1/chendong/aiwork/pretrain_hub/lawyer-llama-13b-beta1.0/pytorch_model-00002-of-00003.bin.58352e4e890197aa518502ba6ea6f4fad0918d01fa64b630562bf163d46754a3.enc with 79 workers
Writing final chunks...
Error: Checksums do not match. The file may be corrupted.  第二个bin模型转化出错
Decrypting file /mnt/nvme0n1/chendong/aiwork/pretrain_hub/lawyer-llama-13b-beta1.0/pytorch_model-00003-of-00003.bin.064ecc317fe7b8f370310f878e952f05553922f3d74d1816023cf2ec4d2f480c.enc with 79 workers
Writing final chunks...
Decryption completed. 我们尝试多次下载7B 和 您开源的13B模型,每次都出现同样错误。是我下载7B的模型问题嘛？

**Comment by ahpuchend** [comment]
![image](https://github.com/AndrewZhe/lawyer-llama/assets/31383929/694692b0-bb7a-4cca-b23e-fbd7647f797a)

**Comment by luciusssss** [comment]
你好，可以试用新版的Lawyer LLaMA 2。新版的模型没有加密。https://github.com/AndrewZhe/lawyer-llama/blob/main/demo/run_inference_v2.md
