### ISSUE TITLE
第四条

### ISSUE THREAD

**Issue by 1553965822** [AndrewZhe/lawyer-llama#59]
从[百度网盘](https://pan.baidu.com/s/1tBkgMzcDe3zZ8Xyf22T7Wg)（提取码：jxqh）下载法条检索模块，并运行其中的python server.py启动法条检索服务，默认挂在9098端口。    这个链接显示不存在了，可以重新分享下吗

**Comment by luciusssss** [comment]
你好，现在可以从HuggingFace下载了 https://huggingface.co/pkupie/marriage_law_retrieval
