### ISSUE TITLE
你好，已更新 https://pan.baidu.com/s/1tBkgMzcDe3zZ8Xyf22T7Wg

### ISSUE THREAD

**Issue by 1553965822** [AndrewZhe/lawyer-llama#60]
你好，已更新 https://pan.baidu.com/s/1tBkgMzcDe3zZ8Xyf22T7Wg
密码:jxqh

_Originally posted by @luciusssss in https://github.com/AndrewZhe/lawyer-llama/issues/53#issuecomment-1880781322_

**Comment by 1553965822** [comment]
还是失效状态

**Comment by luciusssss** [comment]
你好，现在可以从HuggingFace下载了 https://huggingface.co/pkupie/marriage_law_retrieval
