### ISSUE TITLE
检索知识库增强

### ISSUE THREAD

**Issue by yukunren** [AndrewZhe/lawyer-llama#63]
您好 如果我有一些自己的知识库 怎么增加到[marriage_law_retrieval](https://huggingface.co/pkupie/marriage_law_retrieval) 这个模型里面呢

**Comment by luciusssss** [comment]
您好，[marriage_law_retrieval](https://huggingface.co/pkupie/marriage_law_retrieval) 这个模型中的法条是固定的，无法直接添加新的知识。可以使用Langchain等框架引入自己的知识库。
