### ISSUE TITLE
GGUF格式问题

### ISSUE THREAD

**Issue by yangxiaoshuai2333** [AndrewZhe/lawyer-llama#65]
您好，基于这个模型我进行了GGUF格式量化并尝试使用ollama部署，但是感觉性能有非常大程度的下降，请问modelfile的提示词用什么格式的参考么，用llama2和llama3格式的提示均不能正常工作，用qwen格式的提示词和stop正常工作但是感觉性能有较大下降

**Comment by luciusssss** [comment]
您好，提示词可以参考：

https://github.com/AndrewZhe/lawyer-llama/blob/e97a410fe7914bc92b2d12c14d424117de35fd1d/demo/demo_cmd.py#L63-L73
