### ISSUE TITLE
各阶段训练参数的设置问题

### ISSUE THREAD

**Issue by EricLingRui** [AndrewZhe/lawyer-llama#7]
非常棒的工作，感谢作者的开源。
在阅读技术报告的时候，个人产生一些疑问麻烦作者解答下。
Figure 3 中的s12模型，实际上是跨了5个阶段训练的产物，我比较想知道在不同阶段的各种参数是如何进行衔接来避免知识遗忘的？
在我实验设置中，stage 2 使用 stage 1数据的子集来继续微调，如果采用同样的初始学习率等超参，stage 1 中的其它数据就会产生灾难性遗忘。请问你们是如何避免这种情况的？

**Comment by AndrewZhe** [comment]
可以考虑lifelong learning里的replay方法？

比如在训第二阶段的时候，也放一些第一阶段的数据。我们在实验中，发现这种方式能显著减少灾难性遗忘的问题。
